# Generated by Django 6.0.5 on 2026-05-08 22:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CortePescado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Filé (Ex: Salmão Premium)')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição curta (Ex: Sem espinhas, a vácuo)')),
                ('preco_por_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por KG (R$)')),
                ('imagem_url', models.URLField(blank=True, null=True, verbose_name='Link da Foto')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Venda?')),
            ],
            options={
                'verbose_name': 'Corte de Pescado',
                'verbose_name_plural': 'Cortes de Pescado',
            },
        ),
        migrations.CreateModel(
            name='LeadRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ do Cliente')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('virou_cliente', models.BooleanField(default=False)),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Lead (Interessado)',
                'verbose_name_plural': 'Leads (Interessados)',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Pedido')),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro (No ato da entrega)')], default='PIX', max_length=20, verbose_name='Forma de Pagamento')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total (R$)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Pagamento'), ('PAGO', 'Pago!'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status do Pagamento')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funil_vendas.leadrestaurante', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade (KG)')),
                ('preco_na_epoca', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Pago na Época')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funil_vendas.cortepescado', verbose_name='Corte Vendido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='funil_vendas.pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
