# Generated by Django 6.0.5 on 2026-05-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funil_vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrestaurante',
            name='nome_restaurante',
            field=models.CharField(default='Não Informado', max_length=150, verbose_name='Nome do Restaurante'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix (Imediato)'), ('DINHEIRO', 'Dinheiro (No ato da entrega)')], default='PIX', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
