# Generated by Django 6.0.5 on 2026-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funil_vendas', '0002_leadrestaurante_nome_restaurante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data Agendada'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Agendado'),
        ),
    ]
