# Generated by Django 5.2.13 on 2026-05-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funil_vendas', '0003_pedido_data_entrega_pedido_endereco_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortepescado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadrestaurante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
